CREATE TABLE e1_Ciudadano(
	Curp VARCHAR(18) NOT NULL PRIMARY KEY,
	Apellido_Paterno VARCHAR(20),
	Apellido_Materno VARCHAR(20),
	Nombre VARCHAR(20),
	Direccion VARCHAR(20),
	EstadoID INT
);

CREATE TABLE e1_Vehiculo(
	Num_Motor VARCHAR(20) NOT NULL PRIMARY KEY,
	Marca VARCHAR(20),
	Modelo VARCHAR(20),
	Anio INT
);

CREATE TABLE e1_Matricula(
	Placa VARCHAR(7) NOT NULL PRIMARY KEY,
	Curp VARCHAR(18) REFERENCES e1_Ciudadano(Curp) ON DELETE CASCADE ON UPDATE CASCADE,
	Num_Motor VARCHAR(20) REFERENCES e1_Vehiculo(Num_Motor) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE e1_Estado(
	EstadoID INT NOT NULL PRIMARY KEY,
	Estado VARCHAR(20)
);

CREATE TABLE e1_Multas(
	Curp INT REFERENCES e1_Ciudadano(Curp) ON DELETE CASCADE ON UPDATE CASCADE,
	Placa VARCHAR(7) REFERENCES e1_Matricula(Placa) ON DELETE CASCADE ON UPDATE CASCADE,
	Monto INT,
	Fecha_Multa DATE,
	Pagada BOOLEAN,
	Fecha_Pago DATE
);